import Head from 'next/head'
import { Inter } from 'next/font/google'

import { Header, TextField } from '~/shared/ui'
import SendIcon from '/public/icons/send.svg'

const inter = Inter({ subsets: ['latin'] })

export const HomePage = () => {
    return (
        <>
            <Head>
                <title>DWED</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={inter.className}>
                <Header />
                <main className='container'>
                    <TextField icon={{ src: SendIcon.src, alt: 'send' }} />
                </main>
            </div>
        </>
    )
}
