import Head from 'next/head'
import { Inter } from 'next/font/google'

import { Header } from '~/shared/ui'

const inter = Inter({ subsets: ['latin'] })

export const HomePage = () => {
    return (
        <>
            <Head>
                <title>DWED</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={inter.className}>
                <Header />
            </div>
        </>
    )
}
