import Head from 'next/head'
import { Inter } from 'next/font/google'

import SendIcon from '/public/icons/send.svg'
import Play from '/public/icons/play.svg'

import { Header, TextField } from '~/shared/ui'
import { IconButton } from '~/shared/ui/icon-button'
import { Message } from '~/entities/message'
import { StreamPlayer } from '~/entities/stream-player'

const inter = Inter({ subsets: ['latin'] })

export const HomePage = () => {
    return (
        <>
            <Head>
                <title>DWED</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={inter.className}>
                <Header />
                <main className='container'>
                    <TextField icon={{ src: SendIcon.src, alt: 'send' }} />
                    <IconButton icon={{ src: Play.src, alt: 'play' }} />
                    <Message />
                    <StreamPlayer />
                </main>
            </div>
        </>
    )
}
